### ISSUE TITLE
It seems that the innerBackground is not adapting to the circular bar’s barWidth.

### ISSUE THREAD

**Issue by Icelightwwwwww** [philzet/PZCircularControl#1] opened 2021-11-10 16:57 UTC
When innerBackgroundColor isn’t clear color, innerBackground will get overlapped to the circular bar if the barWidth is larger than 10.0, and there’ll be some space between the bar and the innerBackground filled circle if the barWidth is smaller than 10.0. It seems that the innerBackground is not adapting to the circular bar. Of course everything works fine if the innerBackgroundColor is .clear, but if it’s not, it seems that I need to set the barWidth fixed to 10.0.

**Comment by philzet** [comment] 2021-11-13 03:22
I need some help investigating this. Can't reproduce what you're talking about. Do you have an example project?

**Comment by Icelightwwwwww** [comment] 2022-02-15 16:50
This is when the barWidth is 10:
![A0D48D4C-5AB6-43A0-B7C9-6435D80CF1DD](https://user-images.githubusercontent.com/60870648/154107734-294816fa-ab1a-4897-8793-78a6fb232542.jpeg)
This is when the barWidth is 5:
![542294CA-41BD-4A4D-A592-D47C60E963DE](https://user-images.githubusercontent.com/60870648/154107799-3b6a639b-8fba-4df8-a792-ea275d8a5474.jpeg)
This is when the barWidth is 14:
![F4A0FFB7-8132-40A3-AAC2-2C0EEBC33558](https://user-images.githubusercontent.com/60870648/154107872-7bb694f0-7e67-47a5-ace4-a7c1fd652d7c.jpeg)
There’s some space between the outer circular progress bar and the inner Circle. Apparently the overlapped innerBackground (barWidth > 10) looks fine and I(not only me) am expecting that PZCircularcontrol works the same when the barWidth is under 10. I mean, it’ll be better if there’re no space between them.
Btw PZCircularControl is a really good module and I like it very much. Thanks for maintaining this~

**Comment by philzet** [comment] 2022-03-06 17:33
Hi, thanks for spotting this. Any chance you're able to work on it? I don't have the capacity at the moment, so would be helpful in getting the change in quicker.

**Comment by philptr** [comment] 2024-12-24 21:37
Closing as Configuration Changed as the API surface has been reworked for 1.0.0.

**Closed as not planned by philptr** 2024-12-24 21:37 UTC
